apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deployer
  namespace: chatbot
rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
      - deployments/status
      - deployments/scale
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch

  - apiGroups: [""]
    resources:
      - services
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch

  - apiGroups: [""]
    resources:
      - events
    verbs:
      - get
      - list
      - watch

